site_name: OpenOpsToolkit
site_description: OpenOpsToolkit Organization Documentation
site_author: OpenOpsToolkit
site_url: https://OpenOpsToolkit.github.io
nav:
  - Home: index.md
  - DevOps Bootstrap: devops-bootstrap/index.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js