site_name: OpenOpsToolkit
site_description: OpenOpsToolkit DevOps Bootstrap Documentation
site_author: OpenOpsToolkit
site_version: 1.0.0
site_url: https://OpenOpsToolkit.github.io
repo_url: https://github.com/OpenOpsToolkit/devops-bootstrap
nav:
  - Organization: org.md
theme:
  name: material